### ISSUE TITLE
Fine Tuning Failure

### ISSUE THREAD

**Issue by Wei-Qi** [xxlong0/NeuralUDF#6]
Thanks for the great work and for sharing the code. 

I tried to train on objects with closed surfaces (DTU). I first ran the bash: ```bash bashs/bash_dtu_blending.sh --gpu 0 --case scan24```, and got some results.

However, then I ran the bash: ```bash bashs/bash_dtu_blending_ft.sh --gpu 0 --case scan24``` , but in most dtu scans the Fine-tuning results look even worse. What should I do to solve this problem? Besides, in these scans, the results I obtained by using the evaluation script you provided are quite different from those in Table 2 of your paper.

Thanks again!

**Comment by xxlong0** [comment]
Thanks for the information, i will check whether there is a bug and back soon.

________________________________
From: weiqi ***@***.***>
Sent: Saturday, April 8, 2023 11:08:19 PM
To: xxlong0/NeuralUDF ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [xxlong0/NeuralUDF] Fine Tuning Failure (Issue #6)


Thanks for the great work and for sharing the code.

I tried to train on objects with closed surfaces (DTU). I first ran the bash: ``bash bashs/bash_dtu_blending.sh --gpu 0 --case scan24``` , and got some results.

However, then I ran the bash: bash bashs/bash_dtu_blending_ft.sh --gpu 0 --case scan24, but in most dtu scans the Fine-tuning results look even worse. What should I do to solve this problem? Besides, in these scans, the results I obtained by using the evaluation script you provided are quite different from those in Table 2 of your paper.

Thanks again!

**Comment by flamehaze1115** [comment]
> Thanks for the great work and for sharing the code.
> 
> I tried to train on objects with closed surfaces (DTU). I first ran the bash: `bash bashs/bash_dtu_blending.sh --gpu 0 --case scan24`, and got some results.
> 
> However, then I ran the bash: `bash bashs/bash_dtu_blending_ft.sh --gpu 0 --case scan24` , but in most dtu scans the Fine-tuning results look even worse. What should I do to solve this problem? Besides, in these scans, the results I obtained by using the evaluation script you provided are quite different from those in Table 2 of your paper.
> 
> Thanks again!

Dear Weiqi,
I found there indeed exsist some bugs due to conflicted code versions. I will fix the bugs as soon as possible.
Sorry for the inconvinience.

**Comment by Wei-Qi** [comment]
> > Thanks for the great work and for sharing the code.
> > I tried to train on objects with closed surfaces (DTU). I first ran the bash: `bash bashs/bash_dtu_blending.sh --gpu 0 --case scan24`, and got some results.
> > However, then I ran the bash: `bash bashs/bash_dtu_blending_ft.sh --gpu 0 --case scan24` , but in most dtu scans the Fine-tuning results look even worse. What should I do to solve this problem? Besides, in these scans, the results I obtained by using the evaluation script you provided are quite different from those in Table 2 of your paper.
> > Thanks again!
> 
> Dear Weiqi, I found there indeed exsist some bugs due to conflicted code versions. I will fix the bugs as soon as possible. Sorry for the inconvinience.
When you fixe these bugs, could you please reply here？Thank you.

**Comment by flamehaze1115** [comment]
Hello. I have fixed some minor bugs like wrong variable names without changing core codes, and have tested the fine-tuning on scan24. 
In my experiments, in the finetuning, the variance can be optimized to be further smaller, and the reconstruction become more accurate.
If you still fail to reproduce the results, you can directly contact me by wechat: longxiao1115.
